name: build-dockerfile-image
on:
  workflow_call:
    inputs:
      code-lang:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      code-lang:
        required: true
        type: choice
        options: [java, node, python]
jobs:
  call-workflow-in-another-repo:
    uses: ovicorpsystems/workflows/.github/workflows/build-dockerfile-image.yml@main
    secrets: inherit
    with:
      code-lang: ${{ inputs.code-lang }}
