name: Test Docker Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t my-maven-app:test .
          
      - name: Test image (opcional)
        run: |
          docker run --rm my-maven-app:test echo "App compilada OK"
